language: android
jdk: oraclejdk8

env:
  global:
  - ADB_INSTALL_TIMEOUT=10
  matrix:
  - ANDROID_TARGET=android-25  ANDROID_ABI=armeabi-v7a  TEST_SUITE=static

android:
  components:
  - extra-google-m2repository
  - extra-android-m2repository
  - tools
  - platform-tools
  - build-tools-25.0.2
  - android-25

before_install:
  - echo "disablePreDex" >> gradle.properties

before_script:
  - ./gradlew dependencies

script:
  - ./gradlew check
